pipeline:
  install:
    image: kkarczmarczyk/node-yarn:latest
    commands:
      - yarn
    when:
      branch:
        - master
        - feature/*
      event:
        - push
        - pull_request

  lint:
    image: kkarczmarczyk/node-yarn:latest
    commands:
      - yarn lint
    when:
      branch:
        - master
        - feature/*
      event:
        - push
        - pull_request

  test:
    image: kkarczmarczyk/node-yarn:latest
    commands:
      - yarn test
    when:
      branch:
        - master
        - feature/*
      event:
        - push
        - pull_request

  build/ui:
    image: kkarczmarczyk/node-yarn:latest
    environment:
      - NODE_ENV=production
    commands:
      - yarn dist
    when:
      branch:
        - master
        - feature/*
      event:
        - push
        - pull_request

  build/lib:
    image: kkarczmarczyk/node-yarn:latest
    environment:
      - NODE_ENV=production
    commands:
      - yarn lib
    when:
      branch:
        - master
        - feature/*
      event:
        - push
        - pull_request

  deploy/ui:
    image: chekote/gulp:latest
    secrets: [ SSH_HOST, SSH_KEY, SSH_PATH ]
    commands:
      - gulp deploy:production
    when:
      branch:
        - master
      event:
        - push

  publish/lib:
    image: plugins/npm
    secrets: [ NPM_TOKEN, NPM_EMAIL ]
    when:
      branch:
        - master
      event:
        - push
