---
kind: pipeline
name: ci

steps:
  - name: install
    image: iknpx/archnode
    commands:
      - yarn --silent
    when:
      branch:
        - master
        - develop
      event:
        - push
        - pull_request

  - name: lint
    image: iknpx/archnode
    commands:
      - yarn lint
    when:
      branch:
        - master
        - develop
      event:
        - push
        - pull_request

  - name:  test
    image: iknpx/archnode
    commands:
      - yarn test
    when:
      branch:
        - master
        - develop
      event:
        - push
        - pull_request

  - name: build/image-source
    image: iknpx/archnode
    environment:
      NODE_ENV: production
    commands:
      - yarn dist
    when:
      branch:
        - master
        - develop
      event:
        - push

  - name: build/npm-package
    image: iknpx/archnode
    environment:
      NODE_ENV: production
    commands:
      - yarn lib
    when:
      branch:
        - master
        - develop
      event:
        - push

  - name: publish/npm-package
    image: plugins/npm
    settings:
      username:
        from_secret: npm_username
      password:
        from_secret: npm_password
      email:
        from_secret: npm_email
    when:
      branch:
        - master
      event:
        - push

  - name: publish/image
    image: plugins/docker
    settings:
      repo: dayler/ui
      purge: true
      insecure: false
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch:
        - master
      event:
        - push
