---
extends:
  - eslint-config-dayler

settings:
  react:
    version: '16.3'
  import/resolver:
    node:
      moduleDirectory: ['node_modules', './src']
    webpack:
      config: './webpack/index.js'
