---
extends:
  - eslint-config-dayler

settings:
  react:
    version: '16.8.5'
  import/resolver:
    node:
      moduleDirectory: ['node_modules', './src']
    alias:
      - ['home', './']
      - ['app', './app']
      - ['dayler-ui', './src']
