---
extends:
  - eslint-config-dayler

settings:
  react:
    version: '16.8.6'
  import/resolver:
    node:
      moduleDirectory: ['node_modules']
    alias:
      - ['src', './src']
      - ['dayler-ui', './src/lib']
