---
extends:
  - eslint-config-dayler

rules:
  react/display-name:
    - 0

settings:
  react:
    version: '16.8.6'
  import/resolver:
    node:
      moduleDirectory: ['node_modules']
    alias:
      - ['app', './src/app']
      - ['src', './src']
      - ['root', './']
      - ['dayler-ui', './src/lib']
