/**
 * Do not edit this file
 *
 * SSH_HOST : ssh host
 * SSH_KEY  : ssh key
 * SSH_PATH : ssh path
 * SSH_PATH_DEV : ssh dev path
 */

const gulp = require('gulp')
const sftp = require('gulp-sftp')

gulp.task('deploy:production', function () {
    return gulp.src('dist/*')
        .pipe(sftp({
            host: process.env.SSH_HOST,
            keyContents: process.env.SSH_KEY,
            remotePath: process.env.SSH_PATH,
            user: 'root',
            remotePlatform: 'unix',
        }))
})

gulp.task('deploy:dev', function () {
    return gulp.src('dist/*')
        .pipe(sftp({
            host: process.env.SSH_HOST,
            keyContents: process.env.SSH_KEY,
            remotePath: process.env.SSH_PATH_DEV,
            user: 'root',
            remotePlatform: 'unix',
        }))
})
